### ISSUE TITLE
Add IConfigurationRefresher.TryRefresh API

### ISSUE THREAD

**Issue by zhenlan** [Azure/AppConfiguration-DotnetProvider#113]
To make it easier for customers to trigger configuration refresh without worrying about crashing the app due to various transient errors, propose to add the API below in `IConfigurationRefresher`.
```cs
Task<bool> TryRefresh()
```
**Details**
The `TryRefresh` will not throw on Transient or any FailedRequestException, regardless of the status code (even 401, 403)

The existing API `Refresh` will not catch anything.

**More discussion**
Propose to follow the convention and rename APIs to
```cs
Task RefreshAsync();
Task<bool> TryRefreshAsync();
```

**Comment by abhilasharora** [comment]
Closing this issue since the proposed APIs `RefreshAsync` and `TryRefreshAsync` have been released as a part of version `3.0.0` of the package `Microsoft.Extensions.Configuration.AzureAppConfiguration`.

The addition of logging to `TryRefreshAsync` is being tracked at https://github.com/Azure/AppConfiguration-DotnetProvider/issues/134.
