### ISSUE TITLE
Loading Key Vault values is attempted even if ConfigureKeyVault isn't called

### ISSUE THREAD

**Issue by SamaraSoucy-MSFT** [Azure/AppConfiguration-DotnetProvider#139]
Issue originally brought up in the docs repo: https://github.com/MicrosoftDocs/azure-docs/issues/49293

Repro:

1. Setup an App Config instance that contains a Key Vault reference.
2. Configure App Configuration without calling `ConfigureKeyVault()` 
```
[assembly: FunctionsStartup(typeof(FunctionApp.Startup))]
namespace FunctionApp
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var config = new ConfigurationBuilder();

            config.AddEnvironmentVariables();
            TokenCredential credential = new DefaultAzureCredential();
            var endpoint = new Uri(Environment.GetEnvironmentVariable("AppConfigEndpoint"));

            //Setup Azure App Config
            config.AddAzureAppConfiguration(options =>
            {
                options.Connect(endpoint, credential);
            });

            builder.Services.Replace(
                ServiceDescriptor.Singleton(typeof(IConfiguration),
                config.Build()));
        }
    }
}
```
Expected Behavior: App Config provider won't try to load any results from Key Vault.

Actual Behavior: "Microsoft.Extensions.Configuration.AzureAppConfiguration.KeyVaultReferenceException: 'No key vault credential configured and no matching secret client could be found."

This is the same result as when ConfigureKeyVault() is called with a null credential. This means that if there are any Key Vault references in an App Config instance, all the apps using it will need to pass credentials to `ConfigureKeyVault()` even if they won't be using Key Vault references or use `Select()` statements to try to avoid loading any.

**Comment by jimmyca15** [comment]
Hello @SamaraSoucy-MSFT

The appearance of this error, even though `ConfigureKeyVault` is not called, is by design. The secrets that cause the error are in the configuration set that is being queried by the application. If the application is allowed to run when this occurs it results in what we consider to be an undefined state since there is no clear expectation for what should be returned when one of the secrets is accessed by the app.

We can think more about this scenario to figure out a way that makes sense to limit secret resolution. 

In the mean time, name-spacing settings with a prefix or placing settings into separate labels would be a way to solve this problem. This is also a best practice approach for isolating settings that are needed and not needed by the application.

As an example, the application can select only settings that start with "myApp/". Since the application depends on all these settings there shouldn't be any secrets, or if there are secrets it should cause the app to crash if it can't resolve them.

```
            config.AddAzureAppConfiguration(options =>
            {
                options.Connect(endpoint, credential);

                options.Select("myApp/*", LabelFilter.Null);
            });
```

**Comment by SamaraSoucy-MSFT** [comment]
The original thread from the customer was that, while using using labels and prefixes is definitely the preferred way to go, in reality not every team is going to be organized enough to follow a specific naming or labeling convention. All it would take is one misplaced reference to bring down an app not using Key Vault credentials.

Maybe at some point we could consider adding a configuration option to block key vault loading or state that they want the reference, not the Key Vault contents? That covers the scenario the customer brought up of a precautionary measure, as well as any where someone intentionally wants the reference instead of loading the content from Key Vault. The Azure portal is an example of the second scenario- interacting with the contents of the App Config data as opposed to what is in Key Vault.

**Comment by avanigupta** [comment]
Hi @SamaraSoucy-MSFT, please see the proposed solution in #209 and let us know if you have any concerns.
