### ISSUE TITLE
RefreshAsync() should continue retry until success in push model

### ISSUE THREAD

**Issue by zhenlan** [Azure/AppConfiguration-DotnetProvider#180]
@drago-draganov and I had a discussion about this a while back.

It is not a problem `RefreshAsync()` only tries a few times (current behavior) in the pull model because the next call of `RefreshAsync()` will try again. However, in the push model, the next call to `RefreshAsync()` could be far away (in time). It becomes important that the `RefreshAsync()` will retry until success.

In terms of implementation, we don't really have to differentiate push or pull model. We may have to implement our own retry policy to have exponential backoff + jitter if what the SDK has is not sufficient. 
- The retry interval should never be longer than the cache expiration time.
- There is only one instance of `RefreshAsync()` running at a time.

cc: @jimmyca15

**Comment by jimmyca15** [comment]
Good thinking Zhenlan and Drago. That would be quite troublesome for the push model. I am in agreement with the two points laid out. Sounds like that should give the proper retry mechanics to work for pull and push.

**Comment by abhilasharora** [comment]
I looked at the retry implementation in the SDK and the exponential backoff policy does have jitter for randomization. As long as users configure the appropriate retry options for configuration client, both the listed points should be satisfied.

**Comment by zhenlan** [comment]
We need to provide this behavior out of the box. Users don't need to do anything.

**Comment by abhilasharora** [comment]
If we want to configure infinite retries for `RefreshAsync` in case of push model but not for pull model, then we would need to distinguish between those two cases, so I'm not sure I understand how we provide this behavior out of the box.

**Comment by drago-draganov** [comment]
We should not distinguish between pull and push.
________________________________

**Comment by drago-draganov** [comment]
Pull still can be infinite retries
________________________________

**Comment by zhenlan** [comment]
`RefreshAsync` can throw. `TryRefreshAsync` won't. I just use `RefreshAsync` as an example.

**Comment by zhenlan** [comment]
In the pull model, the `TryRefreshAsync` can have the same behavior as long as it satisfies the two bullets above.

**Comment by abhilasharora** [comment]
For `RefreshAsync` to be able to throw, it has to give up retrying at some point, so it can't retry until it succeeds. If `TryRefreshAsync` retries till it succeeds, then it can never return a value of `false`. It will either remain stuck retrying or return `true`. Is the expectation for both methods to have different retry logic?

**Comment by zhenlan** [comment]
Good point. Probably a new API will help. The idea is same though.

**Comment by drago-draganov** [comment]
Throw API doesn't imply we can't retry forever under the hood. It accepts cancelation token to control.

Breaking API call due to internal/hidden number of retries is bad and difficult to control by the immediate caller. What's enough number of attempts? Let the caller decide how to cancel via explicit cancelation token. Drop the magic.
________________________________

**Comment by abhilasharora** [comment]
In the current implementation, the number of retry attempts is limited. This helps ensure that if the application does not have any activity, we do not continue to retry failed attempts to refresh the configuration. In the push model, even when there are no retry attempts for failures, the refresh operation would be re-triggered on the next call to `RefreshAsync`.

I believe the need for retry until failure was felt due to a bug in the refresh code that could lead to an inconsistent state, such the future calls to `RefreshAsync` would miss changes to the configuration. This has been fixed, so we expect the next call to `RefreshAsync` to re-attempt failed refresh.

**Comment by zhenlan** [comment]
As long as `*RefreshAsync` does not reset the "dirty flag" when it fails, looks like it will be fine as you said.
