### ISSUE TITLE
Azure app configuration does not load the configuration when a disabled key vault secret is present.

### ISSUE THREAD

**Issue by bipinraghavan** [Azure/AppConfiguration-DotnetProvider#309]
Hi,
I have an Azure app configuration with 2 keys. Both have key vault references as values. When one of the key-vault secret is disabled for some reason (because expiration date has passed, not needed for now etc.,), entire configuration loading fails after throwing KeyVault reference exception. 
I tried using SetSecretResolver, but it looks like if the registered KV client encounters any exception, secret resolver fallback will not be called. Is there any solution for this issue? Basically, I don't want to stop loading the config, if any or some of the KV secrets are disabled. 
BTW, I tried setting the "Options: true" to suppress the exception throwing, but that did not load the config. 
Thanks in advance for any help.

**Comment by avanigupta** [comment]
Hi @bipinraghavan, Key Vault does not allow read operations on disabled/expired secrets and throws 403 error. This is by design. We never hide the exceptions thrown by KeyVault because that would leave the application configuration in an undefined state. But if you want more control over error handling, you can implement your own secret resolver by using the SetSecretResolver API.

>I tried using SetSecretResolver, but it looks like if the registered KV client encounters any exception, secret resolver fallback will not be called.

That is correct. SetSecretResolver doesn't handle errors thrown by registered SecretClient(s). It will only be used when no SecretClient has been registered with the same vault URI. This GitHub issue has more details about setting up your own secret resolution code: https://github.com/Azure/AppConfiguration-DotnetProvider/issues/209#issuecomment-743427521

Let me know if you need more details.
