### ISSUE TITLE
Mark property as dirty when a KeyVault secret is updated

### ISSUE THREAD

**Issue by israelhdz08** [Azure/AppConfiguration-DotnetProvider#468]
I have an Azure function that receives messages on a service bus every time an App Configuration setting is updated, and then calls `ProcessPushNotification` to mark the setting as dirty and ensure that the next request reloads the value. 

Since some of my App Configuration settings are KeyVault references, I updated the KeyVault to send notifications to this service bus when a secret is updated, the problem is that the message can't be deserialized to a `PushNotification`, so the `ProcessPushNotification` method doesn't work in this case. The `SetDirty` method would be useful here, but it is no longer available. Is there a way to process these notifications using `AzureAppConfigurationRefresher` ?

**Comment by amerjusupovic** [comment]
Hi @israelhdz08, have you already considered [this option for refreshing Key Vault secrets](https://learn.microsoft.com/en-us/azure/azure-app-configuration/reload-key-vault-secrets-dotnet)?

**Comment by samsadsam** [comment]
We offer [EventGridEventExtensions.TryCreatePushNotification](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/0afb56a4ec7b628e0b771a4a34ac7f7694ea8cfd/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/Extensions/EventGridEventExtensions.cs#L23) to convert an [EventGridEvent](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventgrid.eventgridevent?view=azure-dotnet) to a [PushNotification](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/0afb56a4ec7b628e0b771a4a34ac7f7694ea8cfd/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/PushNotification.cs#L11) for convenience, and since it's the main use case our customers use for push notification model.

If another type of event needs to be converted to `PushNotification`, you may write the logic for it.

Closing the issue. Please feel free to re-open it if you need more assistance :)
